namespace SpriteKind {
    export const Penny = SpriteKind.create()
    export const Schnelligkeitstrank = SpriteKind.create()
    export const Stärketrank = SpriteKind.create()
    export const Resistenztrank = SpriteKind.create()
    export const Regnerationstrank = SpriteKind.create()
}
namespace StatusBarKind {
    export const BossHealth = StatusBarKind.create()
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairNorth, function (sprite, location) {
    sprite.y += -10
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Stärketrank, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    SchadenZauberer = -20
    timer.after(40000, function () {
        SchadenZauberer = -10
    })
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    let ZaubererBildRichtung = 0
    if (ZaubererBildRichtung == 0) {
        animation.runImageAnimation(
        Zauberer,
        assets.animation`MagierZaubertAnimation`,
        500,
        false
        )
        projectile = sprites.createProjectileFromSprite(assets.image`LeerBild`, Zauberer, 50, 0)
        projectile.setScale(Scale, ScaleAnchor.Middle)
        pause(500)
        projectile.setImage(assets.image`ProjectileZauberer`)
    } else if (ZaubererBildRichtung == 2) {
        animation.runImageAnimation(
        Zauberer,
        assets.animation`MagierZaubertAnimation`,
        1000,
        false
        )
        projectile = sprites.createProjectileFromSprite(assets.image`LeerBild`, Zauberer, -50, 0)
        projectile.setScale(Scale, ScaleAnchor.Middle)
        pause(500)
        projectile.setImage(assets.image`ProjectileZauberer`)
    }
})
statusbars.onZero(StatusBarKind.BossHealth, function (status) {
    tiles.setTileAt(status.spriteAttachedTo().tilemapLocation(), assets.tile`PortalTile`)
    sprites.destroy(status.spriteAttachedTo(), effects.ashes, 500)
    Zaubertrank = sprites.create(assets.image`Regenerationstrank`, SpriteKind.Regnerationstrank)
    Zaubertrank.sayText("Regnerationstrank")
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Zauberer.vy == 0) {
        Zauberer.vy = -200
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Resistenztrank, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    timer.after(40000, function () {
    	
    })
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`PortalTile`, function (sprite, location) {
    LevelVar += 1
    if (LevelVar == 2) {
        tiles.setCurrentTilemap(tilemap`Bossarena1Tilemap`)
        Zauberer.setPosition(37, 743)
        Geist = sprites.create(assets.image`Geist Normal`, SpriteKind.Enemy)
        statusbar = statusbars.create(20, 4, StatusBarKind.BossHealth)
        statusbar.setColor(10, 8)
        statusbar.attachToSprite(Geist, 0, 0)
        animation.runImageAnimation(
        Geist,
        assets.animation`GeistAngriffAnimation`,
        1000,
        true
        )
        Zaubertrank = sprites.create(assets.image`Stärketrank`, SpriteKind.Stärketrank)
        Zaubertrank.setPosition(720, 582)
        Zaubertrank.sayText("Stärketrank")
        Zaubertrank = sprites.create(assets.image`Resistenztrank`, SpriteKind.Resistenztrank)
        Zaubertrank.setPosition(550, 550)
        Zaubertrank.sayText("Resistenztrank")
    }
    if (LevelVar == 3) {
        tiles.setCurrentTilemap(tilemap`Level2Tilemap`)
        Zauberer.setPosition(37, 519)
    }
    if (LevelVar == 4) {
        tiles.setCurrentTilemap(tilemap`Bossarena2Tilemap`)
        Zauberer.setPosition(37, 720)
        for (let index = 0; index < 10; index++) {
            Spuckball = sprites.create(assets.image`SpukballBild`, SpriteKind.Enemy)
        }
        Spuckball.x = scene.screenWidth()
        Spuckball.y = randint(10, scene.screenHeight())
    }
    if (LevelVar == 5) {
        tiles.setCurrentTilemap(tilemap`Level3Tilemap`)
        Zauberer.setPosition(37, 871)
    }
    if (LevelVar == 6) {
        tiles.setCurrentTilemap(tilemap`Level3`)
        Zauberer.setPosition(37, 871)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Schnelligkeitstrank, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    controller.moveSprite(Zauberer, 200, 0)
    timer.after(40000, function () {
        controller.moveSprite(Zauberer, 100, 0)
    })
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Regnerationstrank, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.setLife(4)
})
sprites.onDestroyed(SpriteKind.Enemy, function (sprite) {
    statusbarpennys += 50
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.ashes, 500)
    statusbars.getStatusBarAttachedTo(StatusBarKind.BossHealth, otherSprite).value += randint(SchadenZauberer - 9, SchadenZauberer)
})
let statusbarpennys = 0
let Spuckball: Sprite = null
let statusbar: StatusBarSprite = null
let Geist: Sprite = null
let projectile: Sprite = null
let SchadenZauberer = 0
let Zaubertrank: Sprite = null
let LevelVar = 0
let Scale = 0
let Zauberer: Sprite = null
tiles.setCurrentTilemap(tilemap`Level1Tilemap`)
let ZaubererBildVar = assets.image`Magier Normal`
Zauberer = sprites.create(ZaubererBildVar, SpriteKind.Player)
Scale = 0.9
Zauberer.setScale(Scale, ScaleAnchor.Middle)
Zauberer.setPosition(20, 199)
controller.moveSprite(Zauberer, 100, 0)
Zauberer.ay = 300
scene.cameraFollowSprite(Zauberer)
LevelVar = 1
info.setLife(4)
Zaubertrank = sprites.create(assets.image`Schnelligkeitstrank`, SpriteKind.Schnelligkeitstrank)
Zaubertrank.setPosition(500, 199)
Zaubertrank.sayText("Schnelligkeit")
SchadenZauberer = -10
let KleinerGeistBild = sprites.create(img`
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdbcbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdcccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdbcbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbb3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffff1fffffff11fffffffffffffffffffdccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffbcbbffff1bbffffffffffffdbbbb3bbccbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff1ccccbfff1cbfffffffffffbbccccbcccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffbccccbfff1ccbffffffffffbbccccccccccbbfffffffffbbb1ffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffbccccccb3f1ccbfffffffffdcccccbccccccccbbbbbffffbccbbbffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffbcccccccbf1bcbfffffffffbbccccbccccccccccccbfffffbccccbfffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffbcccccccbf1bcbfffffffffbbcccbbbbbcccccccccbfbbccccccccbffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffdcccccb1ffbbbffffff1bbbbbbcbbbbbcccccccccbbbccccccccccffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffbbbdffff11bbbb11dbbbbbbbbbbbbbbccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbccbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc3ffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffbddbbcccccbbbbbbbbbbbbbbbbbbbbcccccccccccccccccbfffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffbbbbbcccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccccccbffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffbbccccccccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccccccbfffddddfffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffdbcccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccbfbccccccbfffff1bbbbbbfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffbcccccccccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccccccbbccccccccbbfbbcccccccbbbffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccdbccccccccccbffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccbdffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffbccccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccbbffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffbccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccbbfffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffbcccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbbbbbbccccccccccccccccccccccccccccccfffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffbccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbffffbccccccccccccccccccccccccccccccc1fffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbfff1bcccccccccccccccccccccccccccccccbbffffffffffffffffffff
    ffffffffffffffffffffffbbdffffffffffffffbccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbffbccccccccccccccccccccccccccccccccccffffffffffffffffffff
    fffffffffffffffffffffdccccbfffffffffffffbcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccbbbccccccccccccccccccccccccccccccccccc1ffffffffffffffffff
    ffffffffffffffffffffbcccccbffffffffffffffbccccccccccbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccc1ffffffffffffffffff
    ffffffffffffffffffffbccccccbfffffffffffffbccccccccccccfffffffffffffcccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccc1ffffffffffffffffff
    fffffffffffffffffffbccccccccbfffffffffffffbbcccccccfffffffffffffffffffffccbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffff
    fffffffffffffffffffbcccccccccdfffffffffffffbccccfffffffffffffffffffffffffffcccbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffff
    ffffffffffffffffffffbccccccccdffffffffffffbccfffffffffcffffcccffffffffffffffffcccbbccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffff
    ffffffffffffffffffffbcccccccb1fffffffffffbcfffffffffffcfccccfffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffff
    fffffffffffffffffffffdbccccbbffffffffbbccffffffffcccccccccccccccccfffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccc1ffffffffffffffffff
    fffffffffffffffffffffffbfcffffffbbbccccffffffccccccccccccccccccccccccccfffffffffffffcccccccccccccccccccccccccccccccccccccccccbfbcc1ffffffffffffffffff
    fffffffffffffffffffffffffffffffbcccccffffffccccccccccccccccccccccccccccccfffffffffffffccccccccccccccccccccccccccccccccccccccbfffddfffffffffffffffffff
    fffffffffffffffffffffffffcfffbccccccfffffccccccccccccccccccccccccccccccccffffffffffffffccccccccccccccccccccccccccccccccccccccbfffffffffffffffffffffff
    ffffffffffffffffffffbcbffcfffccccccfffffcccccccccccccccccccccccccccccccccccfffffffffffffccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffff
    ffffffffffffffffffbbbcbffbfffcccccfffffcccccccccccccccccccccccccccccccccccccffffffffffffffccccccccccccccccccccccccccccccccccccbbfffffffffffffffffffff
    fffffffffffffffffbcccccfffffbccccfffffccccccccccccccccccccccccccccccccccccccccfffffffffffffcccccccccccccccccccccccccccccccccccccd1fffffffffffffffffff
    fffffffffffffffbcccccccfccccccccfffffcccccccccccccccccccccccccccccccccccccccccccffffffffffffcccccccccccccccccccccccccccccccccccccc1ffffffffffffffffff
    ffffffffffffffbccccccbcfccccccffffffccccccccccccccccccccccccccccccccccccccccccccfffffffffffffcccccccccccccccccccccccccccccccccccccbffffffffffffffffff
    fffffffffffffbcccccccdffcccccffffffcccccccccccccccccccccccccccccccccccccccccccccccfffffffffffccccccccccccccccccccccccccccccccccccccffffffffffffffffff
    fffffffffffffbcccccccdffccccffffffccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffcccccccccccccccccccccccccccccccccccccddffffffffffffffff
    ffffffffffffbcccccccb1ffccccffffffccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffccccccccccccccccccccccccccccccccccccccffffffffffffffff
    ffffffffffffbccccccc11ffcccffffffccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffcccccccccccccccccccccccccccccccccccccbfffffffffffffff
    ffffffffffffbccccccb11ffcccfffffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffccccccccccccccccccccccccccccccccccccccdffffffffffffff
    ffffffffffffbccccccd11ffccfffffcccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffcccccccccccccccccccccccccccccccccccccdffffffffffffff
    fffffffffffffbccccb111ffcffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffccccccccccccccccccccccccccccccccccccdffffffffffffff
    fffffffffffffbccccd111ffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffcccccccccccccccccccccccccccccccccccbffffffffffffff
    fffffffffffffbbccc1111ffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccffffcffffffffffffcccccccccccccccccccccccccccccccccccbffffffffffffff
    fffffffffffffffccb1111cfffffffccccccccccccccccccccccccccccccccccccccccccccccccccccfffddfffffffffffffccccccccccccccccccccccccccccccccccbffffffffffffff
    ffffffffffffffffcd1111bffffffccccccccccccccccccccccccccccccccccccccccccccccccccccffc111cffffffffffffccccccccccccccccccccccccccccccccccbffffffffffffff
    ffffffffffffffffd11111bffffffcccccccccccccccccccccccccccccccccccccccccccccccccccffc1111bfffffffffffffcccccccccccccccccccccccccccccccccbffffffffffffff
    ffffffffffffffff111111dffffffccccccccccccccccccccccccccccccccccccccccccccccccccffb111111cffffffffffffccccccccccccccccccccccccccccccccb3ffffffffffffff
    ffffffffffffffff1111111fffffccccccccccccccccccccccccccccccccccccccccccccccccccffd1111111bffffffffffffccccccccccccccccccbcccccccccccccffffffffffffffff
    ffffffffffffffff1111111cffffccccccccccccccccccccccccccccccccccccccccccccccccffc111111111dfffffffffffffccccccccccccccccb1bcccccccccccbffffffffffffffff
    fffffffffffffffd1111111bffffcccccccccccccccccccccccccccccccccccccccccccccccffb11111111111cffffffffffffcccccccccccccccccffccccccccccbfffffffffffffffff
    fffffffffffffffd1111111dffffccccccccccccccccccccccccccccccccccccccccccccccfcd111111111111dffffffffffffcccccccccccccccccbdcccccccccb1fffffffffffffffff
    fffffffffff1bffd11111111ffffcccccccccccccccccccccccccccccccccccccccccccccfb111111111111111cffffffffffffcccccccccccccccccccccccccbb1ffffffffffffffffff
    ffffffffffbccffd11111111bfffcccccccccccccccccccccccccccccccccccccccccccffd1111111111111111bffffffffffffcccccccccccccccccccccccccdffffffffffffffffffff
    fffffffffbcccbbd111111111fffcccccccccccccccccccccccccccccccccccccccccffc1111111111111111111cfffffffffffccccccccccccccccccccbccccdffffffffffffffffffff
    fffffffffcccccbd111111111cfffcccccccccccccccccccccccccccccccccccccccffb11111111111111111111cfffffffffffccccccccccccccccccccbfbccdffffffffffffffffffff
    fffffffffbbbbbfd111111111bfffccccccccccccccccccccccccccccccccccccccfcd111111111111111111111bfffffffffffcccccccccccccccccccccbbccdffffffffffffffffffff
    fffffffffffffffd111111111dfffccccccccccccccccccccccccccccccccccccffc11111111111111111111111bffffffffffffccccccccccccccccccccbbcbfffffffffffffffffffff
    fffffffffffffffd1111111111cfffccccccccccccccccccccccccccccccccccffd11111111111111111111111dbffffffffffffccccccccccccccccccccbffffffffffffffffffffffff
    fffffffffffffffd1111111111dfffccccccccccccccccccccccccccccccccffc111111111111111111111111dddffffffffffffccccccccccccccccccccbffffffffffffffffffffffff
    fffffffffffffffd11111111111bfffccccccccccccccccccccccccccccccffb1111111111111111111111111dddffffffffffffccccccccccccccccccccbffffffffffffffffffffffff
    fffffffffffffffd111111111111fffcccccccccccccccccccccccccccccfc11111111111111111111111111ddddffffffffffffcccccccccccccccccccbfffffffffffffffffffffffff
    fffffffffffffffd111111111111dfffccccccccccccccccccccccccccffb1111111111111111111111111ddddddffffffffffffcccccccccccccccccb1ffffffffffffffffffffffffff
    fffffffffffffffd1111111111111cffcccccccccccccccccccccccccfcd11111111111111111111111111ddddddcfffffffffffcccccccccccccccccbfffffffffffffffffffffffffff
    fffffffffffffffd1111111111111cfffccccccccccccccccccccccffb111111111111111111111111111dddddddcfffffffffffcccccccccccccccccdfffffffffffffffffffffffffff
    fffffffffffffffdd111111111111fffffccccccccccccccccccccfcd1cd1111111111111111111111111dddddddcfffffffffffcccccccccccccccccdfffffffbbbbffffffffffffffff
    fffffffffffffffdd11111111111dfcfffccccccccccccccccccffb11dfc111111111111111111111111ddddddddcfffffffffffcccccccccccccccccbbffffffbcccbbbfffffffffffff
    ffffffffffffffffd11111111111bfbdfffccccccccccccccccfcd111dffd1111111111111111111111dddddddddffffffffffffcccccccccccccccccccbffffffdcccccbbfffffffffff
    ffffffffffffffffd11111111111bfd1bffccccccccccccccffb11111dffb111111111111111111111dddddddddbffffffffffffcccccccccccccccccccbfbbbbbbccccccbfffffffffff
    ffffffffffffffffdd11111111111d111cffccccccccccccfc1111111dffc1111111111111111111dddddddddddbfffffffffffccccccccccccccccccccbfbccccccccccccbffffffffff
    ffffffffffffffffdd1111111111111111cffcccccccccffb111111111cfc111111111111111111ddddddddddddcfffffffffffccccccccccccccccccccbbbcccccccccccccffffffffff
    ffffffffffffffffddd1111111111111111ffccccccccccd1111111111dfb11111111111111111dddddddddddddffffffffffffccccccccccccccccccccccccccccccccccbfffffffffff
    fffffffffffffffffddd11111111111111bffcffccccccc111111111111dd1111111111111111dddddddddddddbffffffffffffccccccccccccccccccccccccccccccccccbfffffffffff
    fffffffffffffffffddddd11111111111bfffffffccccccc1111111111111111111111111111ddddddddddddddcfffffffffffccccccccccccccccccccccccccccccccccbffffffffffff
    ffffffffffffffffbcddddd111111111cfffffffffffffccb11111111111111111111111111dddddddddddddddcfffffffffffccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffbcbdddddd11111dccfffffffffccfffccb11111111111111111111111dddddddddddddddddffffffffffffccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffbccbdddddd1111ccfffffffffffffcccccb11111111111111111111ddddddddddddddddddffffffffffffcccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffdddddbddddddbccfffffffffffffffffcccd1111111111111d1111ddddddddddddddddddcffffffffffffcccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffffff1cbbbccfccffffffffffffffffffccccd111111111dddddddddddddddddddddddddcffcffffffffffcccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffffffbcfffffffffffffffffffffffffffccfcdddd1ddddddddddddddddddddddddddddcffcffffffffffccccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffffffbccffffffffffffffffffffffffffcccfc1ddddddddddddddddddddddddddddddbffcfffffffffffccccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffffffbcccffffffffffffffffffffffffffcccfcbddddddddddddddddddddddddddddbffcfffffffffffcccccccccccccccccccccccccccccccccccccfffffffffffff
    ffffffffffffffffffff1ccbcffffffffffffffffffffffffffcccffcddddddddddddddddddddddddddbfccfffffffffffccccccccccccccccccccccccccccccccccccccfffffffffffff
    fffffffffffffffffffffbb1dcffffffffffffffffffffffffffcccfffcddddddddddddddddddddddbcfccffffffffffffccccccccccccccccccccccccccccccccccccbbfffffffffffff
    ffffffffffffffffffffffbcbdbcffffffffffffffffffffffffffccffffcddddddddddddddddddbcffcfffffffffffffccccccccccccccccccccccccccccccccbbbbb3ffffffffffffff
    fffffffffffffffffffffbcccddbcfffffffffffffffffffffffffffcfffffcddddddddddddddbfffccffffffffffffffccccccccccccccccccccccccccccccccffffffffffffffffffff
    ffffffffffffffffffffbccccddceeffffffffffffffffffffffffffffffffffccccccbbbbbcfffcffffffffffffffffcccccccccccccccccccccccccccccccccffffffffffffffffffff
    ffffffffffffffffffffbccccbbcceeecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccccffffffffffffffffffff
    ffffffffffffffffffffbccccccccceeeeecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccbfffffffffffffffffff
    ffffffffffffffffffffbcccccccccceeeeeeeffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccccccbffffffffffffffffff
    ffffffffffffffffffffbccccccccccceeeeeeeeecfffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccbffffffffffffffffff
    ffffffffffffffffffffbcccccccccccceeeeeeeeeeeeeeccffffffffffffffffffffffffffffffcccffffffffffccccccccccccccccccccccccccccccccccccccbbbdfffffffffffffff
    ffffffffffffffffffffbcccccccccccccceeeeeeeeeeeeeeeeeeecccccfffffffcccccceeeeeeeecffffffffffcccccccccccccccccccccccccccccccccccccccccccdffffffffffffff
    ffffffffffffffffffff1ccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeebddddbeeeeeeeefffffffffffcccccccccccccccccccccccccccccccccccccccccccc1ffffffffffffff
    fffffffffffffffffffffbccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddeeeeeeefffffffffffccccccccccccccccccccccccccccccccccccccccccccc1fffffffffffffff
    ffffffffffffffffffffffcccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeedddeeeeeecfffffffffffcccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffff
    ffffffffffffffffffffffdccccccccbcccccccceeeeeeeeeeeeeeeeeeeeeeeeeebdbeeeeefffffffffffccccccccccccccccccccccccccccccb1bcccccccccccccdfffffffffffffffff
    ffffffffffffffffffffff1cccccccbbccccccccccceeeeeeeeeeeeeeeeeeeeeeebdeeeefffffffffffcccccccccccccccccccccccccccccbcbff1cccccccccccb9ffffffffffffffffff
    fffffffffffffffffffffffbbcccccffbcccccccccccceeeeeeeeeeeeeeeeeeeeeebecffffffffffffccccccccccccccccccccccccccccbdbbffffccccccccccbffffffffffffffffffff
    ffffffffffffffffffffffff1cccccffbcccccccccccccfeeeeeeeeeeeeeeeeeeeffffffffffffffcccccccccccccccccccccccccccccdffffffffbccccccccbfffffffffffffffffffff
    fffffffffffffffffffffffffbbbcbf1bccccccccccccccccfffffceeeeeecffffffffffffffffccccccccccccccccccccccccccccccbfffffffffbbbbbbbbdffffffffffffffffffffff
    ffffffffffffffffffffffffffffd1dccccccccccccccccccccfffffffffffffffffffffffffcccccccccccccccccccccccccccccccbfffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffff1bcccccccccccccccccccccccffffffffffffffffccccccccccccccccccccccccccccccccccbfffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffbcccccccccbbccccccccccccccbcccccccccccccccccccccccccccccccccccccccccccccccbffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff3bccccccccb1bccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffbbbcccccb1fbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffdccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffdbccccccccccccccccccccccccccccccccccccccccbcccccccccccccccbfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffddbcccccccccbbcccccccccccccbbbccccccccbfdcccccccccccccccdfffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffbbcccccccbbbcccbbbbbbbbb1fbbccccccc1f1ccccccccccccccbdfffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbccccb3fffffffffffffffffbccccccb1f1bbccccccccbbbdfffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbcccb1ffffffffffffffffffdcccccb1ffffffbbbbbbfffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbccbfffffffffffffffffffbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbcbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `, SpriteKind.Player)
game.onUpdate(function () {
    if (Zauberer.vx > 0 && Zauberer.vy == 0) {
        ZaubererBildVar = assets.image`Magier Normal`
        Zauberer.setImage(ZaubererBildVar)
    } else if (Zauberer.vx < 0 && Zauberer.vy == 0) {
        ZaubererBildVar = assets.image`Magier Normal`
        ZaubererBildVar.flipX()
        Zauberer.setImage(ZaubererBildVar)
    } else if (Zauberer.vy != 0 && Zauberer.vx > 0) {
        ZaubererBildVar = assets.image`ZaubererJumpBild`
        Zauberer.setImage(ZaubererBildVar)
    } else if (Zauberer.vy != 0 && Zauberer.vx < 0) {
        ZaubererBildVar = assets.image`ZaubererJumpBild`
        ZaubererBildVar.flipX()
        Zauberer.setImage(ZaubererBildVar)
    }
    Zauberer.sayText(convertToText(Zauberer.y))
})
